// Shashki
#include "FastGame.h"
#include "Logging.h"


using namespace shashki;


FastGame::FastGame()
{
    /*
        32 bit for men and 32 bit for kings combined into 64 bit number,
        and each bit is 1/0 corresonds to man/king at the position according to below
 
            a   b   c   d   e   f   g   h
        8       0       1       2       3
        7   4       5       6       7   
        6       8       9      10      11
        5   12     13      14      15
        4      16      17      18      19
        3   20     21      23      24   
        2      25      26      27      28
        1   28     29      30      31
    */
    _white = 0x00000000FFF00000;
    _black = 0x0000000000000FFF;
}


FastGame::~FastGame()
{
}


MoveResult
FastGame::move(const Move& move_)
{
    LOG_DEBUG("XXX: " << move_.side() << " " << moveToStr(move_));
    // TODO:
    return MoveResult();
}


std::vector<Move>
FastGame::getAllMoves(Side side_) const
{
    std::vector<Move> moves;

    if (Side::Black == side_)
    {
        // TODO: this part can be autogenerated
        if (0x01 & _black)
        {
            // Move DOWN LEFT
            if (0x08 & _black)
            {
                moves.push_back(Move(0x0801));
            }

            // Move DOWN RIGHT
            if (0x10 & _black)
            {
                moves.push_back(Move(0x1001));
            }

            // TODO: all other cases
        }

        // TODO: all other cases
    }

    // TODO:
    return moves;
}


void
FastGame::dumpCompact(std::ostream& os_) const
{
    // TODO:
}


void
FastGame::dumpNice(std::ostream& os_) const
{
    os_ << "   \033[1;31m";
    for (int8_t i = 0; i < 8; ++i)
    {
        os_ << " " << char('a' + i) << " ";
    }
    os_ << "\033[0m\n";

    for (int8_t i = 0; i < 8; ++i)
    {
        os_ << " \033[1;31m" << 8 - i << " \033[0m";
        for (int8_t j = 0; j < 8; ++j)
        {
            os_ << " ";
            if (not ((i % 2 == 0) xor (j % 2 == 0)))
            {
                os_ << " ";
            }
            else
            {
                auto x = 4 * i + (j / 2);
                if (_white & (1 << x))
                { os_ << "w"; }
                else if (_white & (1 << (x + 32)))
                { os_ << "W"; }
                else if (_black & (1 << x))
                { os_ << "b"; }
                else if (_black & (1 << (x + 32)))
                { os_ << "B"; }
                else
                { os_ << "."; }
            }
            os_ << " ";
        }
        os_ << "\n";
    }
    os_ << "------------------------------" << std::endl;
}

